const fs = require("fs");
const path = require("path");
const file = path.join(__dirname, "/info.json");
const arr = JSON.parse(fs.readFileSync(file, "utf-8"));
console.log(arr);
const item = arr[Math.floor(Math.random() * arr.length)];
console.log(item);
console.log(arr.length);
const id = Math.floor(Math.random() * arr.length + 1);
console.log(id);
arr[id - 1].count = arr[id - 1].count + 1;
fs.writeFileSync(file, JSON.stringify(arr));
